### PR TITLE
allow passing custom button children

### PR DESCRIPTION
**Pull request by LeZuse**
This feature allows you to pass anything as a child of main and children buttons. You can use SVG, text or a whole DOM structure to fit your needs.

### CODE REVIEW

**Comment by phated** [comment]
Can you add a screenshot or add something to the demo for me to test this?  Thanks

**Comment by LeZuse** [comment]
There's a reference to `bundle.js` in the demo, is there a task for it somewhere?

**Comment by phated** [comment]
https://github.com/nobitagit/react-material-floating-button/blob/master/package.json#L24 should be able to build with `npm run bro`

**Comment by phated** [comment]
Merging the other branch put this one out of date and conflicting on the merge.  Please fix that with the demo files.  Thanks!

**Comment by phated** [comment]
@LeZuse ping this thread when you get a chance to update.  Thanks.

**Comment by LeZuse** [comment]
@phated Hi, I've just added a demo showing how custom children work by passing custom text labels. You can display any valid `React.PropTypes.node` actually. I've also rebased against your master to make this mergeable. Sorry it took so long, been busy ...

**Comment by LeZuse** [comment]
stale, feel free to reopen

**Pull request closed without merging**
