### PR TITLE
Make the project more React idiomatic

### PR DESCRIPTION
**Pull request by phated**
This project is really awesome.  Thanks for making it.  I've been doing a bunch of work to make this project more React idiomatic and I wanted to submit a PR to see what you think about the changes.

Let me know what you think.

### CODE REVIEW

**Comment by nobitagit** [comment]
Looks great. I am definitely going to pull it, thanks for the contribution.
It's a big improvement on the first draft, how about me adding you as a collaborator to the repo so you can have direct access?

**Comment by phated** [comment]
Thanks!  I'd definitely be interested in being a collaborator.  I've been working with a lot of react + material design stuff recently.

**Comment by nobitagit** [comment]
:thumbsup: 
Added.
Just starting out with React but it's a much needed breath of fresh air after way too much Angular in the last year or so for me.

ps - don't forget to add your name as author in the package.json if you like.

**Comment by phated** [comment]
@nobitagit will do. Do you think you could add me to the npm package so I can publish a new release?  I've got some more changes to make but I'd like to get the latest published first.

**Comment by nobitagit** [comment]
@phated you should be now listed on npm too.

**Pull request merged**
